const TYPES = {
    // TODOS
    TODOS_LOADING: "TODOS_LOADING",
    TODOS_LOADED: "TODOS_LOADED",
    TODOS_FAILURE: "TODOS_FAILURE",
    TODOS_REBOOT: "TODOS_REBOOT",
    // Todo
    TODO_LOADING: "TODO_LOADING",
    TODO_ADD: "TODO_ADD",
    TODO_FAILURE: "TODO_FAILURE",
}

export default TYPES